//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllotementNotesheetDetail
    {
        public int Id { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public byte[] DigiSignByAssistant { get; set; }
        public string DigiSignByAssistantFileName { get; set; }
        public string DigiSignByAssistantFileType { get; set; }
        public string AssistantComment { get; set; }
        public byte[] DigiSignByManagerProperty { get; set; }
        public string DigiSignByManagerPropertyFileName { get; set; }
        public string DigiSignByManagerPropertyFileType { get; set; }
        public string ManagerPropertyComment { get; set; }
        public byte[] DigiSignBySectionIncharge { get; set; }
        public string DigiSignBySectionInchargeFileName { get; set; }
        public string DigiSignBySectionInchargeFileType { get; set; }
        public string SectionInchargeComment { get; set; }
        public byte[] DigiSignByGMFinance { get; set; }
        public string DigiSignByGMFinanceFileName { get; set; }
        public string DigiSignByGMFinanceFileType { get; set; }
        public string GMFinanceComment { get; set; }
        public byte[] DigiSignByACEO { get; set; }
        public string DigiSignByACEOFileName { get; set; }
        public string DigiSignByACEOFileType { get; set; }
        public string ACEOComment { get; set; }
        public Nullable<System.DateTime> DateoOfSigningByCEO { get; set; }
        public byte[] DigiSignByCEO { get; set; }
        public string DigiSignByCEOFileName { get; set; }
        public string DigiSignByCEOFileType { get; set; }
        public string CEOComment { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ApplicantApplicationDetail ApplicantApplicationDetail { get; set; }
    }
}
