//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allottee_Electronicform
    {
        public long Id { get; set; }
        public Nullable<int> ApplicantId { get; set; }
        public Nullable<int> Plot_Id { get; set; }
        public string Allotment_Number { get; set; }
        public Nullable<System.DateTime> Allotment_Date { get; set; }
        public byte[] Application_Letter_Time_Extension { get; set; }
        public byte[] Affidavit_Self_Attested_Document { get; set; }
        public byte[] Supporting_Proof_Production_Not_Started { get; set; }
        public byte[] Signature_Authorized_Signatory_Verified_Bank { get; set; }
        public byte[] Identity_Proof { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ApplicantApplicationDetail ApplicantApplicationDetail { get; set; }
    }
}
