//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllotmentDetail
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public string AllotmentNo { get; set; }
        public string PlotNo { get; set; }
        public string PaymentStatusByFinance { get; set; }
        public string PaymentStatusByAssistant { get; set; }
        public Nullable<System.DateTime> DateOfInterviewStart { get; set; }
        public Nullable<System.DateTime> DateOfInterviewEnd { get; set; }
        public Nullable<System.DateTime> AllotmentDate { get; set; }
        public Nullable<System.DateTime> DateOfAllotmentLetter { get; set; }
        public Nullable<System.DateTime> DateoOfSigningByCEO { get; set; }
        public byte[] DigiSignByCEO { get; set; }
        public byte[] DigiSignByGMFinance { get; set; }
        public byte[] DigiSignByManagerPropertyGeneralAdmin { get; set; }
        public byte[] DigiSignByAGM_OSD_Sincharge { get; set; }
        public byte[] DigiSignByACEO { get; set; }
        public byte[] DigiSignByAssistant { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ApplicantApplicationDetail ApplicantApplicationDetail { get; set; }
    }
}
