//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlloteeTimeEextensionFfess
    {
        public long Id { get; set; }
        public Nullable<int> PlotId { get; set; }
        public string Number_Year_Time_Extension_Fees { get; set; }
        public Nullable<int> Rate_Time_Extension_Fees { get; set; }
        public string Current_Premium_Plot_Area { get; set; }
        public Nullable<decimal> Total_Time_Extension_Fees { get; set; }
        public string Bank_Account_Number { get; set; }
        public string Bank_Name { get; set; }
        public string Branch_Name { get; set; }
        public Nullable<int> ApplicantId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
