//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllocateAllotmentDetail
    {
        public int Id { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public string AllotmentNumber { get; set; }
        public Nullable<System.DateTime> AllotmentDate { get; set; }
        public Nullable<System.DateTime> StartingDateofInterview_L { get; set; }
        public Nullable<System.DateTime> EndDateofInterview_L { get; set; }
        public Nullable<System.DateTime> DateofAllotmentLetter { get; set; }
        public byte[] CEO_Sign { get; set; }
        public string CEO_SignFileType { get; set; }
        public string CEO_SignFileName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    }
}
