//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantApplicationStatu
    {
        public int Id { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AllotmentId { get; set; }
        public Nullable<decimal> AmountDue { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<bool> PaymentStatusByFinance { get; set; }
        public Nullable<bool> PaymentStatusByAssistant { get; set; }
        public string CommentByAssistant { get; set; }
        public Nullable<bool> InvitationLetterStatus { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ApplicantApplicationDetail ApplicantApplicationDetail { get; set; }
    }
}
