//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeProjectDetail
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public Nullable<int> AllotmentId { get; set; }
        public byte[] DPRForNewProject { get; set; }
        public string AreaToBeUsedForProject { get; set; }
        public string QuantityEffluentDischargedByNewProject { get; set; }
        public string EffluentDischargedStatusForNewProject { get; set; }
        public byte[] NOCFromPCB { get; set; }
        public string ProvisionalSSIRegistrationNoOrIEMsubmittedToSIA { get; set; }
        public string ObnoxiousGasEmissionDetrimentalSurroundings { get; set; }
        public byte[] DulySignedNotarizedForAcknowledged { get; set; }
        public byte[] UploadedSignPhoto { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
