//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaseDeedDetail
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public Nullable<int> AllotmentId { get; set; }
        public Nullable<decimal> EarnestMoneyPaid { get; set; }
        public string EarnestMoneyChallanNo { get; set; }
        public Nullable<decimal> AllotmentMoneyPaid { get; set; }
        public Nullable<decimal> RequiredStampValue { get; set; }
        public string BankGauranteeChallanNo { get; set; }
        public Nullable<decimal> PurchasedStampValue { get; set; }
        public Nullable<decimal> StampValueForBankGaurantee { get; set; }
        public Nullable<System.DateTime> BankGauranteeDate { get; set; }
        public string BankAddressOfGauranteeTaken { get; set; }
        public string EntityNameBehalfOfApplicant { get; set; }
        public byte[] DigiSignByCEO { get; set; }
        public byte[] DigiSignByAMFinance { get; set; }
        public byte[] DigiSignByManagerPropertyGeneralAdmin { get; set; }
        public byte[] DigiSignByAssistant { get; set; }
        public string LeaseDeedAction { get; set; }
        public string LeaseDeedStatus { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
