//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeasdeedNotesheet
    {
        public long Id { get; set; }
        public string ApplicationId { get; set; }
        public Nullable<int> ApplicantId { get; set; }
        public Nullable<System.DateTime> Bankguranteedate { get; set; }
        public string Bankaddress { get; set; }
        public string Allotmentnumber { get; set; }
        public byte[] Digsign_Propassist { get; set; }
        public string Comment_Propassist { get; set; }
        public byte[] Digsign_Manager { get; set; }
        public string Comment_Manager { get; set; }
        public byte[] Digsign_FManager { get; set; }
        public string Comment_FManager { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
    }
}
