//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagerElectronicForm
    {
        public long Id { get; set; }
        public Nullable<int> ApplicantId { get; set; }
        public Nullable<int> PlotId { get; set; }
        public string Allotment_Number { get; set; }
        public Nullable<System.DateTime> Allotment_Date { get; set; }
        public string LandTransfer_OrderNo { get; set; }
        public string Plot_Name { get; set; }
        public string Sector_Name { get; set; }
        public string Plot_Area { get; set; }
        public Nullable<int> Plot_Dormant_NoOfMonth { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ApplicantApplicationDetail ApplicantApplicationDetail { get; set; }
    }
}
