//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManufacturingUnitDetail
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public Nullable<int> AllotmentId { get; set; }
        public Nullable<bool> LeaseDeedDone { get; set; }
        public string ApplicationFormForAddNewProduct { get; set; }
        public byte[] DPRForNewProduct { get; set; }
        public byte[] AuthorisedSignByBank { get; set; }
        public byte[] ApplicantIdedentityProof { get; set; }
        public byte[] SignOfCandidate { get; set; }
        public byte[] PhotoOfCandidate { get; set; }
        public string PollutionCreatedByNewProduct { get; set; }
        public string QualityOfPollutantByNewProduct { get; set; }
        public string ObnoxiousGasDetails { get; set; }
        public string DischargeLiquidEffluents { get; set; }
        public byte[] NOCFromThePollutionControlBoard { get; set; }
        public byte[] RevisedSSIRegistration_IEM { get; set; }
        public string TotalLandCoverageAreaAfterAddingNewProduct { get; set; }
        public string ExceedDesignatedPlotArea { get; set; }
        public string ConstitutionOwnershipLicense { get; set; }
        public byte[] NotarizedAffidavit { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ApplicantApplicationDetail ApplicantApplicationDetail { get; set; }
    }
}
