//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plot_Restoration
    {
        public long Id { get; set; }
        public string Name_Sender_Post { get; set; }
        public string Addressed_To { get; set; }
        public string Subject_Mentioned { get; set; }
        public string Coupon_Number_Old { get; set; }
        public string Sender_Address { get; set; }
        public string Pincode { get; set; }
        public byte[] Document_Upload { get; set; }
        public Nullable<decimal> Processing_Fees { get; set; }
        public Nullable<decimal> Amount_Paid { get; set; }
        public string Transaction_Number { get; set; }
        public Nullable<int> Applicant_Id { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
