//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlotMaster
    {
        public int PlotId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> SchemeType { get; set; }
        public Nullable<int> SchemeName { get; set; }
        public Nullable<int> SectorName { get; set; }
        public Nullable<int> PlotRange { get; set; }
        public string PlotArea { get; set; }
        public string NoOfPlots { get; set; }
        public string PlotRate { get; set; }
        public Nullable<bool> PlotSideCorner { get; set; }
        public Nullable<bool> PlotSideWideRoad { get; set; }
        public Nullable<bool> PlotSideParkFacing { get; set; }
        public string RateForPlotSide { get; set; }
        public string PlotCategory { get; set; }
        public string PercentageRate { get; set; }
        public string PlotCost { get; set; }
        public string ExtraCharge { get; set; }
        public string GrandTotalCost { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
