//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlotTransferDetail
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public Nullable<int> AllotmentId { get; set; }
        public string ApplicantName { get; set; }
        public string ApplicantFathersName { get; set; }
        public string ApplicantAddress { get; set; }
        public string AllotmentNo { get; set; }
        public Nullable<System.DateTime> DateOfAllotment { get; set; }
        public string PlotFullyPaidOrNot { get; set; }
        public Nullable<bool> MortgageToAnyFinancialInstitute { get; set; }
        public byte[] ShowGidaNOCToBank { get; set; }
        public byte[] BabkNOCRepaymentOfLoan { get; set; }
        public string TransferrerGotPlotFormTransferByAnotherTransferee { get; set; }
        public Nullable<decimal> CompletePaymentOfMaintainanceCharge { get; set; }
        public Nullable<decimal> MaintainanceChargePaidAmount { get; set; }
        public Nullable<decimal> CompletePaymentOfLeaseRent { get; set; }
        public Nullable<decimal> LeaseRentPaidAmount { get; set; }
        public string NoOfPremiumPaidInstallment { get; set; }
        public Nullable<decimal> TotalPremiumPaidInstallmentAmount { get; set; }
        public string NoOfInterestPaidInstallment { get; set; }
        public Nullable<decimal> TotalInterestPaidAmount { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDeate { get; set; }
    }
}
