//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PossessionDetail
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public Nullable<int> AllotmentId { get; set; }
        public string PlotNo { get; set; }
        public string SectorLocation { get; set; }
        public Nullable<System.DateTime> TransferDateTime { get; set; }
        public string LayoutOfPlot { get; set; }
        public string BuildingDetails { get; set; }
        public string AreaOfLand { get; set; }
        public string PossessionHandedOverNameBehalfOfGida { get; set; }
        public byte[] DigiSignOfAMCivilOrJECivil { get; set; }
        public byte[] WitnessDetailsFromGida { get; set; }
        public byte[] WitnessDetailsFromAllottee { get; set; }
        public Nullable<System.DateTime> PossessionDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
