//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchemewiseTermsCondition
    {
        public int Id { get; set; }
        public Nullable<int> SchemeName { get; set; }
        public Nullable<System.DateTime> AllotmentMoneyDueDate { get; set; }
        public Nullable<System.DateTime> Firstduedateofpaymentofinterest { get; set; }
        public Nullable<System.DateTime> DateofgivingfirstInstallment { get; set; }
        public Nullable<System.DateTime> DateofgivingsecondInstallment { get; set; }
        public Nullable<System.DateTime> DateofgivingthirdInstallent { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    }
}
