//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferrerUploadDoc
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public Nullable<int> AllotmentId { get; set; }
        public byte[] RequestLetterTransferOfPlot { get; set; }
        public byte[] BuildingPlanDulyApprovedByGida { get; set; }
        public byte[] DocumentsShareholdingDulyCertifiedByCA { get; set; }
        public byte[] MeterSealingCertificate_ProofElectricity { get; set; }
        public byte[] PowerBillLastThreeYears { get; set; }
        public byte[] RawMaterialPurchaseBillLastThreeYears { get; set; }
        public byte[] SalesBillFinishedProductLastThreeYears { get; set; }
        public byte[] GSTFillingReturnLastThreeConsecutiveYears { get; set; }
        public byte[] SupportingDocumentsInCaseOfExemptions { get; set; }
        public byte[] UndertakingOfTransfer { get; set; }
        public byte[] TransferrerSignVerifiedByBank { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
