//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransfereeUploadDoc
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public Nullable<int> AllotmentId { get; set; }
        public byte[] ProjectProfileDulySignedByapplicant { get; set; }
        public byte[] ProposedLandUtilizationPlanDulySignedByApplicant { get; set; }
        public byte[] IdentityProof { get; set; }
        public byte[] TransfereeSignVerifiedByBank { get; set; }
        public byte[] CertificateOfIncorporation { get; set; }
        public byte[] MemorandumAndArticlesOfAssociation { get; set; }
        public byte[] ListOfShareHoldersDirectors { get; set; }
        public byte[] BoardResolution { get; set; }
        public byte[] CompanyProfile { get; set; }
        public byte[] NetWorthOrTurnover { get; set; }
        public byte[] SalesCertificate { get; set; }
        public byte[] CertificateIssuedByDirectorateIndustry { get; set; }
        public byte[] CopyOfCancelCheque { get; set; }
        public byte[] CertificateOfReservedCategory { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
